yoda_event_homepage:
    path:     /hello/{name}/{count}
    defaults: { _controller: YodaEventBundle:Default:index }
yoda_event_homepage_2:
    path:     /test
    defaults: { _controller: YodaEventBundle:Default:test }
foo_bar_event_import:
    resource: "@YodaEventBundle/Resources/config/routing/event.yml"
    prefix:   /event