yoda_event_homepage:
    path:     /hello/{name}/{count}
    defaults: { _controller: YodaEventBundle:Default:index }
yoda_event_homepage_2:
    path:     /test
    defaults: { _controller: YodaEventBundle:Default:test }
foo_bar_event_import:
    resource: "@YodaEventBundle/Resources/config/routing/event.yml"
    prefix:   /event
EionventBundle_event_annotation:
    resource: "@YodaEventBundle/Controller"
    prefix:   /event
    type:     annotation
    
event_register:
    path:     /register
    defaults: { _controller: "YodaEventBundle:Registration:register" }
    

event_login:
    path:     /login
    defaults: { _controller: "YodaEventBundle:Security:login" }
    
jobplix_user_security:
    resource: "@YodaEventBundle/Resources/config/routing/security.xml"