yoda_event_homepage:
    path:     /hello/{name}/{count}
    defaults: { _controller: YodaEventBundle:Default:index }
yoda_event_homepage_2:
    path:     /test
    defaults: { _controller: YodaEventBundle:Default:test }
yoda_event_save:
    path:     /save
    defaults: { _controller: YodaEventBundle:Default:save }

EventBundle_event_annotation:
    resource: "@YodaEventBundle/Controller"
    prefix:   /
    type:     annotation
    
EventBundle_event:
    resource: "@YodaEventBundle/Resources/config/routing/event.yml"
    prefix:   /event